### ISSUE TITLE
Name of the app

### ISSUE THREAD

**Issue by rinigus** [piggz/sailfish-fpd-community-test#2]
I wonder if we should come up with some shorter name for an app. Namely the visible on app grid, on the main page, and cover. As for project name, that should be OK. 

Also, do you plan to push it to the Harbour? It probably doesn't go against the policy, but I don't know for sure. If you do, should it generate something like harbour-xxxx RPM?

**Comment by piggz** [comment]
Agree with the name.  I wasnt planning on putting it on harbour, its more of a helper app to assist porters with FP support, I dont see a use for end users, do you?

**Comment by rinigus** [comment]
Its way easier to add / remove fingerprints. And I am curious whether it works with the official FPD as well. If does, all this asking for PIN before fingerprint operations is "security by obscurity" type.

But we don't have to put into harbour, it is mainly of interest to the porters.
